[package]
name = "cmake-init"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.3", features = ["derive"] }
inquire = "0.7.1"
minijinja = "1.0.12"
regex = "1.10.3"
